# Generated by Django 5.1.3 on 2024-11-11 16:35

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('practice_hub_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=500)),
                ('patient_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('first_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_notification_result', models.CharField(blank=True, choices=[('success', 'success'), ('error', 'error')], max_length=255, null=True)),
                ('second_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('second_notification_result', models.CharField(blank=True, choices=[('success', 'success'), ('error', 'error')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='ProjectConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_first_notification', models.BooleanField(default=True, verbose_name='Enable first notification 24 prior to the appointment')),
                ('hours_before_second_notification', models.IntegerField(default=3, verbose_name='Hours before second appointment notification in the same day')),
            ],
            options={
                'verbose_name': 'Project configuration',
                'verbose_name_plural': 'Project configurations',
            },
        ),
    ]
