# Generated by Django 5.1.3 on 2024-11-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_scraper', '0002_auto_create_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfiguration',
            name='name_of_the_default_whatsapp_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of the default whatsapp user used by the scraper to send phone numbers'),
        ),
    ]
