# Generated by Django 5.1.3 on 2024-11-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_scraper', '0003_projectconfiguration_name_of_the_default_whatsapp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
