# Generated by Django 5.1.3 on 2024-12-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_scraper', '0004_appointment_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
